project:
  type: book

book:
  title: "P12 - listing reprex"
  author: "Ryan Vogt"
  date: "7/6/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand

editor: visual

